const NATIONALITIES = [
  { name: "Argentina", flag: "🇦🇷", liga: "LPF", icon: "<img src='assets/LPF.png' class='trophy-img'>" },
  { name: "Francia", flag: "🇫🇷", liga: "Ligue 1", icon: "<img src='assets/Ligue1.png' class='trophy-img'>" },
  { name: "Brasil", flag: "🇧🇷", liga: "Brasileirão", icon: "<img src='assets/Brasileirao.png' class='trophy-img'>" },
  { name: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", liga: "Premier League", icon: "<img src='assets/PremierLeague.png' class='trophy-img'>" },
  { name: "Bélgica", flag: "🇧🇪", liga: "Pro League", icon: "<img src='assets/ProLeague.png' class='trophy-img'>" },
  { name: "Croacia", flag: "🇭🇷", liga: "HNL", icon: "<img src='assets/HNL.png' class='trophy-img'>" },
  { name: "Países Bajos", flag: "🇳🇱", liga: "Eredivisie", icon: "<img src='assets/Eredivisie.png' class='trophy-img'>" },
  { name: "Portugal", flag: "🇵🇹", liga: "Primeira Liga", icon: "<img src='assets/PrimeiraLiga.png' class='trophy-img'>" },
  { name: "Italia", flag: "🇮🇹", liga: "Serie A", icon: "<img src='assets/SerieA.png' class='trophy-img'>" },
  { name: "España", flag: "🇪🇸", liga: "La Liga", icon: "<img src='assets/LaLiga.png' class='trophy-img'>" }
];
// js/data.js

const TEAMS_BY_COUNTRY = {
  "Argentina": [
    { nombre: "River Plate", rating: 78 },
    { nombre: "Boca Juniors", rating: 77 },
    { nombre: "Racing Club", rating: 75 },
    { nombre: "Estudiantes LP", rating: 74 },
    { nombre: "Talleres (C)", rating: 74 },
    { nombre: "Vélez Sarsfield", rating: 74 },
    { nombre: "San Lorenzo", rating: 73 },
    { nombre: "Independiente", rating: 73 },
    { nombre: "Defensa y Justicia", rating: 72 },
    { nombre: "Argentinos Juniors", rating: 72 },
    { nombre: "Lanús", rating: 72 },
    { nombre: "Huracán", rating: 71 },
    { nombre: "Godoy Cruz", rating: 71 },
    { nombre: "Rosario Central", rating: 71 },
    { nombre: "Newell's Old Boys", rating: 70 },
    { nombre: "Belgrano (C)", rating: 70 },
    { nombre: "Unión (SF)", rating: 69 },
    { nombre: "Gimnasia LP", rating: 69 },
    { nombre: "Tigre", rating: 68 },
    { nombre: "Atlético Tucumán", rating: 68 },
    { nombre: "Platense", rating: 68 },
    { nombre: "Banfield", rating: 68 },
    { nombre: "Instituto (C)", rating: 67 },
    { nombre: "Central Córdoba (SdE)", rating: 66 },
    { nombre: "Barracas Central", rating: 66 },
    { nombre: "Sarmiento (J)", rating: 65 },
    { nombre: "Riestra", rating: 64 },
    { nombre: "Independiente Rivadavia", rating: 64 }
  ],
  "Brasil": [
    { nombre: "Flamengo", rating: 80 },
    { nombre: "Palmeiras", rating: 80 },
    { nombre: "Botafogo", rating: 78 },
    { nombre: "Atlético Mineiro", rating: 78 },
    { nombre: "Fluminense", rating: 77 },
    { nombre: "São Paulo", rating: 77 },
    { nombre: "Internacional", rating: 76 },
    { nombre: "Grêmio", rating: 76 },
    { nombre: "Corinthians", rating: 76 },
    { nombre: "Cruzeiro", rating: 75 },
    { nombre: "Bahia", rating: 74 },
    { nombre: "Vasco da Gama", rating: 74 },
    { nombre: "Athletico Paranaense", rating: 74 },
    { nombre: "Red Bull Bragantino", rating: 73 },
    { nombre: "Fortaleza", rating: 73 },
    { nombre: "Cuibá", rating: 70 },
    { nombre: "Juventude", rating: 69 },
    { nombre: "Criciúma", rating: 69 },
    { nombre: "Atlético Goianiense", rating: 68 },
    { nombre: "Vitória", rating: 68 }
  ],
  "España": [
    { nombre: "Real Madrid", rating: 89 },
    { nombre: "FC Barcelona", rating: 87 },
    { nombre: "Atlético de Madrid", rating: 84 },
    { nombre: "Athletic Club", rating: 81 },
    { nombre: "Real Sociedad", rating: 80 },
    { nombre: "Girona FC", rating: 79 },
    { nombre: "Villarreal CF", rating: 79 },
    { nombre: "Real Betis", rating: 78 },
    { nombre: "Sevilla FC", rating: 77 },
    { nombre: "Valencia CF", rating: 76 },
    { nombre: "CA Osasuna", rating: 75 },
    { nombre: "RC Celta de Vigo", rating: 75 },
    { nombre: "Getafe CF", rating: 74 },
    { nombre: "Rayo Vallecano", rating: 74 },
    { nombre: "RCD Mallorca", rating: 74 },
    { nombre: "UD Las Palmas", rating: 73 },
    { nombre: "Deportivo Alavés", rating: 73 },
    { nombre: "RCD Espanyol", rating: 72 },
    { nombre: "Real Valladolid", rating: 71 },
    { nombre: "CD Leganés", rating: 71 }
  ],
  "Inglaterra": [
    { nombre: "Manchester City", rating: 89 },
    { nombre: "Arsenal", rating: 87 },
    { nombre: "Liverpool", rating: 87 },
    { nombre: "Chelsea", rating: 83 },
    { nombre: "Aston Villa", rating: 82 },
    { nombre: "Tottenham Hotspur", rating: 82 },
    { nombre: "Newcastle United", rating: 82 },
    { nombre: "Manchester United", rating: 81 },
    { nombre: "Brighton & Hove Albion", rating: 79 },
    { nombre: "West Ham United", rating: 78 },
    { nombre: "Fulham", rating: 77 },
    { nombre: "Crystal Palace", rating: 77 },
    { nombre: "Bournemouth", rating: 76 },
    { nombre: "Wolverhampton Wanderers", rating: 76 },
    { nombre: "Brentford", rating: 76 },
    { nombre: "Everton", rating: 75 },
    { nombre: "Nottingham Forest", rating: 75 },
    { nombre: "Leicester City", rating: 74 },
    { nombre: "Ipswich Town", rating: 72 },
    { nombre: "Southampton", rating: 72 }
  ],
  "Italia": [
    { nombre: "Inter de Milán", rating: 86 },
    { nombre: "Atalanta", rating: 83 },
    { nombre: "Juventus", rating: 83 },
    { nombre: "AC Milan", rating: 83 },
    { nombre: "SSC Napoli", rating: 82 },
    { nombre: "AS Roma", rating: 81 },
    { nombre: "SS Lazio", rating: 80 },
    { nombre: "Fiorentina", rating: 79 },
    { nombre: "Bologna", rating: 78 },
    { nombre: "Torino", rating: 76 },
    { nombre: "Udinese", rating: 75 },
    { nombre: "Genoa", rating: 75 },
    { nombre: "Monza", rating: 74 },
    { nombre: "Parma", rating: 73 },
    { nombre: "Hellas Verona", rating: 73 },
    { nombre: "Cagliari", rating: 73 },
    { nombre: "Lecce", rating: 72 },
    { nombre: "Empoli", rating: 72 },
    { nombre: "Como", rating: 72 },
    { nombre: "Venezia", rating: 71 }
  ]
};

// Generamos ALL_TEAMS dinámicamente agregando el país a cada club
const ALL_TEAMS = Object.entries(TEAMS_BY_COUNTRY).flatMap(([pais, equipos]) =>
  equipos.map(e => ({ ...e, pais }))
);

const FORMATION_433 = [
  { code: "POR", nombre: "Portero",               top: 90, left: 50 },
  { code: "LD",  nombre: "Lateral Derecho",       top: 73, left: 84 },
  { code: "DFC", nombre: "Defensa Central",       top: 76, left: 62 },
  { code: "DFC", nombre: "Defensa Central",       top: 76, left: 38 },
  { code: "LI",  nombre: "Lateral Izquierdo",     top: 73, left: 16 },
  { code: "MCD", nombre: "Mediocentro Defensivo", top: 54, left: 50 },
  { code: "MC",  nombre: "Mediocentro",           top: 44, left: 70 },
  { code: "MC",  nombre: "Mediocentro",           top: 44, left: 30 },
  { code: "ED",  nombre: "Extremo Derecho",       top: 18, left: 84 },
  { code: "DC",  nombre: "Delantero Centro",      top: 10, left: 50 },
  { code: "EI",  nombre: "Extremo Izquierdo",     top: 18, left: 16 }
];

const PREFERRED = [
  { code: "POR", statPrimaria: "VIN", statSecundaria: "ATA" },
  { code: "LD",  statPrimaria: "ASI", statSecundaria: "ENT" },
  { code: "DFC", statPrimaria: "ENT", statSecundaria: "VIN" },
  { code: "DFC", statPrimaria: "ENT", statSecundaria: "VIN" },
  { code: "LI",  statPrimaria: "ASI", statSecundaria: "ENT" },
  { code: "MCD", statPrimaria: "REC", statSecundaria: "INT" },
  { code: "MC",  statPrimaria: "ASI", statSecundaria: "GOL" },
  { code: "MC",  statPrimaria: "ASI", statSecundaria: "GOL" },
  { code: "ED",  statPrimaria: "GOL", statSecundaria: "ASI" },
  { code: "DC",  statPrimaria: "GOL", statSecundaria: "ASI" },
  { code: "EI",  statPrimaria: "GOL", statSecundaria: "ASI" }
];