const NATIONALITIES = [
  { name: "Argentina", flag: "🇦🇷", liga: "LPF", region: "CONMEBOL", icon: "<img src='assets/trophies/LPF.png' class='trophy-img'>" },
  { name: "Francia", flag: "🇫🇷", liga: "Ligue 1", region: "UEFA", icon: "<img src='assets/trophies/Ligue1.png' class='trophy-img'>" },
  { name: "Brasil", flag: "🇧🇷", liga: "Brasileirão", region: "CONMEBOL", icon: "<img src='assets/trophies/Brasileirao.png' class='trophy-img'>" },
  { name: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", liga: "Premier League", region: "UEFA", icon: "<img src='assets/trophies/PremierLeague.png' class='trophy-img'>" },
  { name: "Bélgica", flag: "🇧🇪", liga: "Pro League", region: "UEFA", icon: "<img src='assets/trophies/ProLeague.png' class='trophy-img'>" },
  { name: "Croacia", flag: "🇭🇷", liga: "HNL", region: "UEFA", icon: "<img src='assets/trophies/HNL.png' class='trophy-img'>" },
  { name: "Países Bajos", flag: "🇳🇱", liga: "Eredivisie", region: "UEFA", icon: "<img src='assets/trophies/Eredivisie.png' class='trophy-img'>" },
  { name: "Portugal", flag: "🇵🇹", liga: "Primeira Liga", region: "UEFA", icon: "<img src='assets/trophies/PrimeiraLiga.png' class='trophy-img'>" },
  { name: "Italia", flag: "🇮🇹", liga: "Serie A", region: "UEFA", icon: "<img src='assets/trophies/SerieA.png' class='trophy-img'>" },
  { name: "España", flag: "🇪🇸", liga: "La Liga", region: "UEFA", icon: "<img src='assets/trophies/LaLiga.png' class='trophy-img'>" },
  { name: "Alemania", flag: "🇩🇪", liga: "Bundesliga", region: "UEFA", icon: "<img src='assets/trophies/Bundesliga.png' class='trophy-img'>" },
  { name: "Marruecos", flag: "🇲🇦", liga: "Botola Pro", region: "CAF", icon: "<img src='assets/trophies/BotolaPro.png' class='trophy-img'>" },
  { name: "Uruguay", flag: "🇺🇾", liga: "Primera División", region: "CONMEBOL", icon: "<img src='assets/trophies/PrimeraDivision_UY.png' class='trophy-img'>" },
  { name: "Colombia", flag: "🇨🇴", liga: "Liga BetPlay", region: "CONMEBOL", icon: "<img src='assets/trophies/LigaBetPlay.png' class='trophy-img'>" },
  { name: "México", flag: "🇲🇽", liga: "Liga MX", region: "CONCACAF", icon: "<img src='assets/trophies/LigaMX.png' class='trophy-img'>" },
  { name: "Estados Unidos", flag: "🇺🇸", liga: "MLS", region: "CONCACAF", icon: "<img src='assets/trophies/MLS.png' class='trophy-img'>" },
  { name: "Senegal", flag: "🇸🇳", liga: "Ligue 1 Pro", region: "CAF", icon: "<img src='assets/trophies/Ligue1Pro_SN.png' class='trophy-img'>" },
  { name: "Japón", flag: "🇯🇵", liga: "J1 League", region: "AFC", icon: "<img src='assets/trophies/J1League.png' class='trophy-img'>" },
  { name: "Suiza", flag: "🇨🇭", liga: "Super League", region: "UEFA", icon: "<img src='assets/trophies/SuperLeague_CH.png' class='trophy-img'>" },
  { name: "Irán", flag: "🇮🇷", liga: "Persian Gulf Pro League", region: "AFC", icon: "<img src='assets/trophies/PersianGulfProLeague.png' class='trophy-img'>" },
  { name: "Dinamarca", flag: "🇩🇰", liga: "Superliga", region: "UEFA", icon: "<img src='assets/trophies/Superliga_DK.png' class='trophy-img'>" }
];
// js/data.js

const TEAMS_BY_COUNTRY = {
  "Argentina": [
    { nombre: "River Plate", rating: 95 },
    { nombre: "Boca Juniors", rating: 93 },
    { nombre: "Racing Club", rating: 89 },
    { nombre: "Estudiantes LP", rating: 86 },
    { nombre: "Talleres (C)", rating: 86 },
    { nombre: "Vélez Sarsfield", rating: 86 },
    { nombre: "San Lorenzo", rating: 84 },
    { nombre: "Independiente", rating: 84 },
    { nombre: "Defensa y Justicia", rating: 82 },
    { nombre: "Argentinos Juniors", rating: 82 },
    { nombre: "Lanús", rating: 82 },
    { nombre: "Huracán", rating: 80 },
    { nombre: "Godoy Cruz", rating: 80 },
    { nombre: "Rosario Central", rating: 80 },
    { nombre: "Newell's Old Boys", rating: 78 },
    { nombre: "Belgrano (C)", rating: 78 },
    { nombre: "Unión (SF)", rating: 75 },
    { nombre: "Gimnasia LP", rating: 75 },
    { nombre: "Tigre", rating: 74 },
    { nombre: "Atlético Tucumán", rating: 74 },
    { nombre: "Platense", rating: 74 },
    { nombre: "Banfield", rating: 74 },
    { nombre: "Instituto (C)", rating: 71 },
    { nombre: "Central Córdoba (SdE)", rating: 69 },
    { nombre: "Barracas Central", rating: 69 },
    { nombre: "Sarmiento (J)", rating: 67 },
    { nombre: "Riestra", rating: 65 },
    { nombre: "Independiente Rivadavia", rating: 65 }
  ],
  "Francia": [
    { nombre: "Paris Saint-Germain", rating: 99 },
    { nombre: "Olympique de Marseille", rating: 92 },
    { nombre: "AS Monaco", rating: 91 },
    { nombre: "Olympique Lyonnais", rating: 90 },
    { nombre: "LOSC Lille", rating: 89 },
    { nombre: "Stade Rennais", rating: 88 },
    { nombre: "OGC Nice", rating: 88 },
    { nombre: "RC Lens", rating: 87 },
    { nombre: "Stade de Reims", rating: 84 },
    { nombre: "Strasbourg", rating: 83 },
    { nombre: "Stade Brestois 29", rating: 83 },
    { nombre: "FC Nantes", rating: 82 },
    { nombre: "Montpellier HSC", rating: 82 },
    { nombre: "Toulouse FC", rating: 81 },
    { nombre: "AJ Auxerre", rating: 79 },
    { nombre: "Angers SCO", rating: 78 },
    { nombre: "Le Havre AC", rating: 78 },
    { nombre: "FC Lorient", rating: 77 },
    { nombre: "FC Metz", rating: 76 },
    { nombre: "AS Saint-Étienne", rating: 76 }
  ],
  "Brasil": [
    { nombre: "Flamengo", rating: 99 },
    { nombre: "Palmeiras", rating: 98 },
    { nombre: "Botafogo", rating: 95 },
    { nombre: "Atlético Mineiro", rating: 95 },
    { nombre: "Fluminense", rating: 93 },
    { nombre: "São Paulo", rating: 93 },
    { nombre: "Internacional", rating: 90 },
    { nombre: "Grêmio", rating: 90 },
    { nombre: "Corinthians", rating: 90 },
    { nombre: "Cruzeiro", rating: 89 },
    { nombre: "Bahia", rating: 86 },
    { nombre: "Vasco da Gama", rating: 86 },
    { nombre: "Athletico Paranaense", rating: 86 },
    { nombre: "Red Bull Bragantino", rating: 84 },
    { nombre: "Fortaleza", rating: 84 },
    { nombre: "Cuibá", rating: 78 },
    { nombre: "Juventude", rating: 75 },
    { nombre: "Criciúma", rating: 75 },
    { nombre: "Atlético Goianiense", rating: 74 },
    { nombre: "Vitória", rating: 74 }
  ],
  "Inglaterra": [
    { nombre: "Manchester City", rating: 99 },
    { nombre: "Arsenal", rating: 97 },
    { nombre: "Liverpool", rating: 97 },
    { nombre: "Chelsea", rating: 92 },
    { nombre: "Aston Villa", rating: 91 },
    { nombre: "Tottenham Hotspur", rating: 91 },
    { nombre: "Newcastle United", rating: 91 },
    { nombre: "Manchester United", rating: 89 },
    { nombre: "Brighton & Hove Albion", rating: 87 },
    { nombre: "West Ham United", rating: 86 },
    { nombre: "Fulham", rating: 85 },
    { nombre: "Crystal Palace", rating: 85 },
    { nombre: "Bournemouth", rating: 84 },
    { nombre: "Wolverhampton Wanderers", rating: 84 },
    { nombre: "Brentford", rating: 84 },
    { nombre: "Everton", rating: 83 },
    { nombre: "Nottingham Forest", rating: 83 },
    { nombre: "Leicester City", rating: 81 },
    { nombre: "Ipswich Town", rating: 79 },
    { nombre: "Southampton", rating: 79 }
  ],
  "Bélgica": [
    { nombre: "Club Brugge", rating: 90 },
    { nombre: "Union Saint-Gilloise", rating: 89 },
    { nombre: "Anderlecht", rating: 88 },
    { nombre: "KRC Genk", rating: 87 },
    { nombre: "Royal Antwerp", rating: 87 },
    { nombre: "KAA Gent", rating: 86 },
    { nombre: "Standard Liège", rating: 83 },
    { nombre: "KV Mechelen", rating: 81 },
    { nombre: "Cercle Brugge", rating: 81 },
    { nombre: "KVC Westerlo", rating: 80 },
    { nombre: "OH Leuven", rating: 79 },
    { nombre: "Sint-Truidense VV", rating: 78 },
    { nombre: "Sporting Charleroi", rating: 78 },
    { nombre: "KV Kortrijk", rating: 77 },
    { nombre: "RWDM", rating: 75 },
    { nombre: "KAS Eupen", rating: 74 }
  ],
  "Croacia": [
    { nombre: "Dinamo Zagreb", rating: 88 },
    { nombre: "Hajduk Split", rating: 85 },
    { nombre: "NK Osijek", rating: 80 },
    { nombre: "HNK Rijeka", rating: 80 },
    { nombre: "NK Lokomotiva Zagreb", rating: 76 },
    { nombre: "NK Istra 1961", rating: 74 },
    { nombre: "NK Varaždin", rating: 73 },
    { nombre: "HNK Gorica", rating: 73 },
    { nombre: "NK Slaven Belupo", rating: 72 },
    { nombre: "HNK Šibenik", rating: 71 }
  ],
  "Países Bajos": [
    { nombre: "PSV Eindhoven", rating: 93 },
    { nombre: "Ajax", rating: 92 },
    { nombre: "Feyenoord", rating: 92 },
    { nombre: "AZ Alkmaar", rating: 88 },
    { nombre: "FC Twente", rating: 86 },
    { nombre: "FC Utrecht", rating: 84 },
    { nombre: "Vitesse", rating: 82 },
    { nombre: "sc Heerenveen", rating: 81 },
    { nombre: "Sparta Rotterdam", rating: 80 },
    { nombre: "Go Ahead Eagles", rating: 79 },
    { nombre: "NEC Nijmegen", rating: 79 },
    { nombre: "Fortuna Sittard", rating: 78 },
    { nombre: "PEC Zwolle", rating: 78 },
    { nombre: "Heracles Almelo", rating: 77 },
    { nombre: "RKC Waalwijk", rating: 76 },
    { nombre: "Almere City", rating: 75 },
    { nombre: "Excelsior", rating: 75 },
    { nombre: "FC Volendam", rating: 74 }
  ],
  "Portugal": [
    { nombre: "Benfica", rating: 94 },
    { nombre: "FC Porto", rating: 93 },
    { nombre: "Sporting CP", rating: 93 },
    { nombre: "SC Braga", rating: 89 },
    { nombre: "Vitória SC", rating: 85 },
    { nombre: "FC Famalicão", rating: 82 },
    { nombre: "Boavista", rating: 80 },
    { nombre: "Rio Ave", rating: 79 },
    { nombre: "Gil Vicente", rating: 79 },
    { nombre: "Portimonense", rating: 78 },
    { nombre: "Casa Pia", rating: 78 },
    { nombre: "Estoril Praia", rating: 77 },
    { nombre: "GD Chaves", rating: 76 },
    { nombre: "FC Arouca", rating: 76 },
    { nombre: "Estrela da Amadora", rating: 75 },
    { nombre: "FC Vizela", rating: 75 },
    { nombre: "Moreirense", rating: 75 },
    { nombre: "SC Farense", rating: 74 }
  ],
  "Italia": [
    { nombre: "Inter de Milán", rating: 99 },
    { nombre: "Atalanta", rating: 95 },
    { nombre: "Juventus", rating: 95 },
    { nombre: "AC Milan", rating: 95 },
    { nombre: "SSC Napoli", rating: 94 },
    { nombre: "AS Roma", rating: 92 },
    { nombre: "SS Lazio", rating: 91 },
    { nombre: "Fiorentina", rating: 89 },
    { nombre: "Bologna", rating: 89 },
    { nombre: "Torino", rating: 86 },
    { nombre: "Udinese", rating: 84 },
    { nombre: "Genoa", rating: 84 },
    { nombre: "Monza", rating: 83 },
    { nombre: "Parma", rating: 82 },
    { nombre: "Hellas Verona", rating: 82 },
    { nombre: "Cagliari", rating: 82 },
    { nombre: "Lecce", rating: 80 },
    { nombre: "Empoli", rating: 80 },
    { nombre: "Como", rating: 80 },
    { nombre: "Venezia", rating: 79 }
  ],
  "España": [
    { nombre: "Real Madrid", rating: 99 },
    { nombre: "FC Barcelona", rating: 97 },
    { nombre: "Atlético de Madrid", rating: 94 },
    { nombre: "Athletic Club", rating: 90 },
    { nombre: "Real Sociedad", rating: 89 },
    { nombre: "Girona FC", rating: 88 },
    { nombre: "Villarreal CF", rating: 88 },
    { nombre: "Real Betis", rating: 87 },
    { nombre: "Sevilla FC", rating: 86 },
    { nombre: "Valencia CF", rating: 84 },
    { nombre: "CA Osasuna", rating: 84 },
    { nombre: "RC Celta de Vigo", rating: 84 },
    { nombre: "Getafe CF", rating: 82 },
    { nombre: "Rayo Vallecano", rating: 82 },
    { nombre: "RCD Mallorca", rating: 82 },
    { nombre: "UD Las Palmas", rating: 81 },
    { nombre: "Deportivo Alavés", rating: 81 },
    { nombre: "RCD Espanyol", rating: 80 },
    { nombre: "Real Valladolid", rating: 79 },
    { nombre: "CD Leganés", rating: 79 }
  ],
  "Alemania": [
    { nombre: "Bayern Munich", rating: 99 },
    { nombre: "Bayer Leverkusen", rating: 97 },
    { nombre: "Borussia Dortmund", rating: 94 },
    { nombre: "RB Leipzig", rating: 93 },
    { nombre: "VfB Stuttgart", rating: 90 },
    { nombre: "Eintracht Frankfurt", rating: 89 },
    { nombre: "Borussia Mönchengladbach", rating: 86 },
    { nombre: "VfL Wolfsburg", rating: 86 },
    { nombre: "SC Freiburg", rating: 85 },
    { nombre: "TSG Hoffenheim", rating: 85 },
    { nombre: "Werder Bremen", rating: 84 },
    { nombre: "FC Augsburg", rating: 83 },
    { nombre: "Mainz 05", rating: 83 },
    { nombre: "1. FC Union Berlin", rating: 82 },
    { nombre: "1. FC Köln", rating: 81 },
    { nombre: "VfL Bochum", rating: 80 },
    { nombre: "FC St. Pauli", rating: 79 },
    { nombre: "Holstein Kiel", rating: 78 }
  ],
  "Marruecos": [
    { nombre: "Wydad Casablanca", rating: 84 },
    { nombre: "Raja Casablanca", rating: 83 },
    { nombre: "AS FAR Rabat", rating: 81 },
    { nombre: "FUS Rabat", rating: 79 },
    { nombre: "Berkane", rating: 78 },
    { nombre: "MAS Fès", rating: 76 },
    { nombre: "OC Safi", rating: 75 },
    { nombre: "IR Tanger", rating: 74 },
    { nombre: "Hassania Agadir", rating: 73 },
    { nombre: "Moghreb Tétouan", rating: 72 },
    { nombre: "JS Soualem", rating: 71 },
    { nombre: "UTS Rabat", rating: 70 },
    { nombre: "Chabab Mohammédia", rating: 69 },
    { nombre: "CAY Berrechid", rating: 68 },
    { nombre: "MC Oujda", rating: 68 },
    { nombre: "SCC Mohammédia", rating: 67 }
  ],
  "Uruguay": [
    { nombre: "Peñarol", rating: 88 },
    { nombre: "Nacional", rating: 87 },
    { nombre: "Defensor Sporting", rating: 82 },
    { nombre: "Liverpool (UY)", rating: 81 },
    { nombre: "Boston River", rating: 79 },
    { nombre: "Cerro", rating: 77 },
    { nombre: "Plaza Colonia", rating: 76 },
    { nombre: "Montevideo Wanderers", rating: 76 },
    { nombre: "Danubio", rating: 75 },
    { nombre: "River Plate (UY)", rating: 75 },
    { nombre: "Fénix", rating: 74 },
    { nombre: "Deportivo Maldonado", rating: 74 },
    { nombre: "Racing (UY)", rating: 73 },
    { nombre: "Cerro Largo", rating: 73 },
    { nombre: "Progreso", rating: 72 },
    { nombre: "Rampla Juniors", rating: 71 }
  ],
  "Colombia": [
    { nombre: "Atlético Nacional", rating: 88 },
    { nombre: "América de Cali", rating: 85 },
    { nombre: "Millonarios", rating: 85 },
    { nombre: "Deportivo Cali", rating: 83 },
    { nombre: "Independiente Medellín", rating: 83 },
    { nombre: "Junior", rating: 82 },
    { nombre: "Deportes Tolima", rating: 81 },
    { nombre: "Santa Fe", rating: 81 },
    { nombre: "Águilas Doradas", rating: 80 },
    { nombre: "Once Caldas", rating: 79 },
    { nombre: "Alianza Petrolera", rating: 78 },
    { nombre: "Deportivo Pereira", rating: 78 },
    { nombre: "Atlético Bucaramanga", rating: 77 },
    { nombre: "La Equidad", rating: 77 },
    { nombre: "Deportivo Pasto", rating: 76 },
    { nombre: "Jaguares de Córdoba", rating: 75 },
    { nombre: "Envigado", rating: 74 },
    { nombre: "Boyacá Chicó", rating: 74 },
    { nombre: "Fortaleza CEIF", rating: 73 },
    { nombre: "Patriotas Boyacá", rating: 72 }
  ],
  "México": [
    { nombre: "América", rating: 92 },
    { nombre: "Monterrey", rating: 90 },
    { nombre: "Tigres UANL", rating: 89 },
    { nombre: "Guadalajara", rating: 87 },
    { nombre: "Pachuca", rating: 86 },
    { nombre: "Cruz Azul", rating: 86 },
    { nombre: "Toluca", rating: 85 },
    { nombre: "León", rating: 84 },
    { nombre: "Santos Laguna", rating: 83 },
    { nombre: "Pumas UNAM", rating: 83 },
    { nombre: "Atlas", rating: 82 },
    { nombre: "Necaxa", rating: 81 },
    { nombre: "Puebla", rating: 80 },
    { nombre: "Querétaro", rating: 79 },
    { nombre: "Mazatlán", rating: 78 },
    { nombre: "Tijuana", rating: 78 },
    { nombre: "Juárez", rating: 77 },
    { nombre: "Atlético San Luis", rating: 77 }
  ],
  "Estados Unidos": [
    { nombre: "Inter Miami", rating: 90 },
    { nombre: "Los Angeles FC", rating: 89 },
    { nombre: "Columbus Crew", rating: 88 },
    { nombre: "FC Cincinnati", rating: 87 },
    { nombre: "Seattle Sounders", rating: 86 },
    { nombre: "Atlanta United", rating: 85 },
    { nombre: "New York Red Bulls", rating: 84 },
    { nombre: "Orlando City", rating: 84 },
    { nombre: "LA Galaxy", rating: 83 },
    { nombre: "Philadelphia Union", rating: 83 },
    { nombre: "New England Revolution", rating: 82 },
    { nombre: "Portland Timbers", rating: 82 },
    { nombre: "New York City FC", rating: 82 },
    { nombre: "Nashville SC", rating: 81 },
    { nombre: "Austin FC", rating: 81 },
    { nombre: "FC Dallas", rating: 80 },
    { nombre: "Sporting Kansas City", rating: 80 },
    { nombre: "Houston Dynamo", rating: 80 },
    { nombre: "Charlotte FC", rating: 79 },
    { nombre: "Minnesota United", rating: 79 },
    { nombre: "Vancouver Whitecaps", rating: 79 },
    { nombre: "CF Montréal", rating: 78 },
    { nombre: "DC United", rating: 78 },
    { nombre: "Real Salt Lake", rating: 78 },
    { nombre: "Colorado Rapids", rating: 77 },
    { nombre: "Chicago Fire", rating: 77 },
    { nombre: "St. Louis City SC", rating: 77 },
    { nombre: "San Jose Earthquakes", rating: 76 },
    { nombre: "Toronto FC", rating: 75 }
  ],
  "Senegal": [
    { nombre: "Teungueth FC", rating: 78 },
    { nombre: "ASC Jaraaf", rating: 77 },
    { nombre: "Génération Foot", rating: 76 },
    { nombre: "Diambars", rating: 75 },
    { nombre: "AS Pikine", rating: 74 },
    { nombre: "Dakar Sacré-Cœur", rating: 73 },
    { nombre: "AS Douanes (SN)", rating: 73 },
    { nombre: "Casa Sport", rating: 72 },
    { nombre: "Stade de Mbour", rating: 71 },
    { nombre: "US Gorée", rating: 71 },
    { nombre: "Linguère", rating: 70 },
    { nombre: "Guédiawaye FC", rating: 70 },
    { nombre: "NGB Niary Tally", rating: 69 },
    { nombre: "Sonacos", rating: 68 }
  ],
  "Japón": [
    { nombre: "Kawasaki Frontale", rating: 86 },
    { nombre: "Yokohama F. Marinos", rating: 86 },
    { nombre: "Urawa Red Diamonds", rating: 85 },
    { nombre: "Kashima Antlers", rating: 84 },
    { nombre: "Vissel Kobe", rating: 84 },
    { nombre: "Nagoya Grampus", rating: 83 },
    { nombre: "Sanfrecce Hiroshima", rating: 82 },
    { nombre: "FC Tokyo", rating: 81 },
    { nombre: "Cerezo Osaka", rating: 81 },
    { nombre: "Gamba Osaka", rating: 80 },
    { nombre: "Avispa Fukuoka", rating: 79 },
    { nombre: "Shonan Bellmare", rating: 78 },
    { nombre: "Albirex Niigata", rating: 78 },
    { nombre: "Júbilo Iwata", rating: 77 },
    { nombre: "Sagan Tosu", rating: 77 },
    { nombre: "Hokkaido Consadole Sapporo", rating: 76 },
    { nombre: "Kyoto Sanga", rating: 76 },
    { nombre: "Tokyo Verdy", rating: 75 },
    { nombre: "Kashiwa Reysol", rating: 75 },
    { nombre: "Machida Zelvia", rating: 74 }
  ],
  "Suiza": [
    { nombre: "BSC Young Boys", rating: 87 },
    { nombre: "FC Basel", rating: 85 },
    { nombre: "FC Zürich", rating: 84 },
    { nombre: "Servette FC", rating: 83 },
    { nombre: "FC Lugano", rating: 82 },
    { nombre: "FC St. Gallen", rating: 81 },
    { nombre: "FC Luzern", rating: 80 },
    { nombre: "FC Winterthur", rating: 78 },
    { nombre: "Grasshopper Club", rating: 78 },
    { nombre: "FC Lausanne-Sport", rating: 77 },
    { nombre: "Yverdon-Sport", rating: 76 },
    { nombre: "FC Stade Lausanne Ouchy", rating: 75 }
  ],
  "Irán": [
    { nombre: "Persépolis", rating: 83 },
    { nombre: "Esteghlal", rating: 82 },
    { nombre: "Sepahan", rating: 82 },
    { nombre: "Tractor", rating: 81 },
    { nombre: "Foolad", rating: 79 },
    { nombre: "Gol Gohar", rating: 78 },
    { nombre: "Zob Ahan", rating: 77 },
    { nombre: "Aluminium Arak", rating: 76 },
    { nombre: "Mes Rafsanjan", rating: 76 },
    { nombre: "Malavan", rating: 75 },
    { nombre: "Nassaji Mazandaran", rating: 74 },
    { nombre: "Havadar", rating: 73 },
    { nombre: "Sanat Naft", rating: 72 },
    { nombre: "Paykan", rating: 72 },
    { nombre: "Esteghlal Khuzestan", rating: 71 },
    { nombre: "Shams Azar", rating: 71 }
  ],
  "Dinamarca": [
    { nombre: "FC Copenhague", rating: 87 },
    { nombre: "FC Midtjylland", rating: 86 },
    { nombre: "Brøndby IF", rating: 84 },
    { nombre: "FC Nordsjælland", rating: 83 },
    { nombre: "Aarhus GF", rating: 81 },
    { nombre: "Silkeborg IF", rating: 80 },
    { nombre: "Aalborg BK", rating: 79 },
    { nombre: "Odense BK", rating: 78 },
    { nombre: "Randers FC", rating: 78 },
    { nombre: "Viborg FF", rating: 77 },
    { nombre: "SønderjyskE", rating: 76 },
    { nombre: "Vejle BK", rating: 75 }
  ]
};

// Generamos ALL_TEAMS dinámicamente agregando el país a cada club
const ALL_TEAMS = Object.entries(TEAMS_BY_COUNTRY).flatMap(([pais, equipos]) =>
  equipos.map(e => ({ ...e, pais }))
);

const FORMATION_433 = [
  { code: "POR", nombre: "Portero",               top: 90, left: 50 },
  { code: "LD",  nombre: "Lateral Derecho",       top: 73, left: 84 },
  { code: "DFC", nombre: "Defensa Central",       top: 76, left: 62 },
  { code: "DFC", nombre: "Defensa Central",       top: 76, left: 38 },
  { code: "LI",  nombre: "Lateral Izquierdo",     top: 73, left: 16 },
  { code: "MCD", nombre: "Mediocentro Defensivo", top: 54, left: 50 },
  { code: "MC",  nombre: "Mediocentro",           top: 44, left: 70 },
  { code: "MC",  nombre: "Mediocentro",           top: 44, left: 30 },
  { code: "ED",  nombre: "Extremo Derecho",       top: 18, left: 84 },
  { code: "DC",  nombre: "Delantero Centro",      top: 10, left: 50 },
  { code: "EI",  nombre: "Extremo Izquierdo",     top: 18, left: 16 }
];

const PREFERRED = [
  { code: "POR", statPrimaria: "ATA", statSecundaria: "VIN" },
  { code: "LD",  statPrimaria: "ASI", statSecundaria: "ENT" },
  { code: "DFC", statPrimaria: "ENT", statSecundaria: "VIN" },
  { code: "DFC", statPrimaria: "ENT", statSecundaria: "VIN" },
  { code: "LI",  statPrimaria: "ASI", statSecundaria: "ENT" },
  { code: "MCD", statPrimaria: "REC", statSecundaria: "INT" },
  { code: "MC",  statPrimaria: "ASI", statSecundaria: "GOL" },
  { code: "MC",  statPrimaria: "ASI", statSecundaria: "GOL" },
  { code: "ED",  statPrimaria: "GOL", statSecundaria: "ASI" },
  { code: "DC",  statPrimaria: "GOL", statSecundaria: "ASI" },
  { code: "EI",  statPrimaria: "GOL", statSecundaria: "ASI" }
];

const NATIONAL_CUPS = [
  { country: "Argentina", name: "Copa Argentina", icon: "assets/trophies/CopaArgentina.png" },
  { country: "Brasil", name: "Copa do Brasil", icon: "assets/trophies/CopaDoBrasil.png" },
  { country: "España", name: "Copa del Rey", icon: "assets/trophies/CopaDelRey.png" },
  { country: "Inglaterra", name: "FA Cup", icon: "assets/trophies/FACup.png" },
  { country: "Italia", name: "Coppa Italia", icon: "assets/trophies/CoppaItalia.png" },
  { country: "Francia", name: "Coupe de France", icon: "assets/trophies/CoupeDeFrance.png" },
  { country: "Bélgica", name: "Copa de Bélgica", icon: "assets/trophies/CopaBelgica.png" },
  { country: "Croacia", name: "Copa de Croacia", icon: "assets/trophies/CopaCroacia.png" },
  { country: "Países Bajos", name: "KNVB Beker", icon: "assets/trophies/KNVBBeker.png" },
  { country: "Portugal", name: "Taça de Portugal", icon: "assets/trophies/TacaDePortugal.png" }
];

const REGION_PURCHASING_POWER = {
  "Argentina": 0.25,
  "Brasil": 0.5,
  "España": 1.6,
  "Inglaterra": 2.2,
  "Italia": 1.3,
  "Francia": 1.0,
  "Bélgica": 0.7,
  "Croacia": 0.4,
  "Países Bajos": 1.1,
  "Portugal": 0.9
};

const topRegionTrophies = [
  {
    region: "CONMEBOL",
    name: "Copa Libertadores",
    icon: "assets/trophies/CopaLibertadores.png"
  },
  {
    region: "UEFA",
    name: "Champions League",
    icon: "assets/trophies/UCL.png"
  },
  {
    region: "CONCACAF",
    name: "CONCACAF Champions Cup",
    icon: "assets/trophies/CONCACAFChampionsCup.png"
  },
  {
    region: "AFC",
    name: "AFC Champions League Elite",
    icon: "assets/trophies/AFCChampionsLeagueElite.png"
  }
];

const secRegionTrophies = [
  {
    region: "CONMEBOL",
    name: "Copa Sudamericana",
    icon: "assets/trophies/CopaSudamericana.png"
  },
  {
    region: "UEFA",
    name: "Europa League",
    icon: "assets/trophies/Europa League.png"
  },
  {
    region: "CONCACAF",
    name: "CONCACAF Central American Cup",
    icon: "assets/trophies/CONCACAFCentralAmericanCup.png"
  },
  {
    region: "AFC",
    name: "AFC Cup",
    icon: "assets/trophies/AFCCup.png"
  }
];